apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik-v2-helm.fullname" . }}
  labels:
    {{- include "traefik-v2-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: internal
      protocol: TCP
      name: internal
  selector:
    {{- include "traefik-v2-helm.selectorLabels" . | nindent 4 }}
